# Default configurations for tags
fast:
  cafe060043121032: # 3
    enable: true
    sync_frequency: 14
    transmit_frequency: 6
    alias: '10-1F'

  cafe060043042148: # 0
    enable: true
    sync_frequency: 14
    transmit_frequency: 6
    alias: '10-1M'

  cafe060043045445: # 2
    enable: true
    sync_frequency: 14
    transmit_frequency: 6
    alias: '2'

  cafe060043045146: # 1
    enable: true
    sync_frequency: 14
    transmit_frequency: 6
    alias: '1'

  cafe060043121448: # 4
    enable: true
    sync_frequency: 14
    transmit_frequency: 6
    alias: '10-1M'

  deca000000009640:
    enable: false
    sync_frequency: 14
    transmit_frequency: 6
    alias: 'TAG-1'

  deca000000009740:
    enable: false
    sync_frequency: 14
    transmit_frequency: 6
    alias: 'TAG-2'

  deca000000000100:
    enable: false
    sync_frequency: 14
    transmit_frequency: 6
    alias: 'PDOA-1'

